version: '3.7'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: memesdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./app/src:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    networks:
      - backend

  media_service:
    build:
      context: .
      dockerfile: media_service/Dockerfile
    volumes:
      - ./media_service/src:/app/media_service
    ports:
      - "8001:8001"
    depends_on:
      - minio
    networks:
      - backend

volumes:
  postgres_data:
  minio_data:

networks:
  backend:
