version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: memesdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d memesdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: memesdb
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy

  app_tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - minio
      - mad_soft
    command: [ "pytest", "/mad_soft/tests" ]
